server:
  port: 8083
  servlet:
    context-path: /manager

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: Karry0921
    url: jdbc:mysql://bj.kevinkda.cn:3306/WebService202005?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true&useUnicode=true&useSSL=true&allowPublicKeyRetrieval=true
    username: kevin
#    type: com.alibaba.druid.pool.DruidDataSource
